### ISSUE TITLE
ERR_INVALID_ARG_TYPE while using Plugin in CLI

### ISSUE THREAD

**Issue by polisvfx** [backbeatmedia/nexrender-comp-sequence#1]
`> job rendering failed
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.readFileSync (node:fs:451:42)
    at new EnhancedScript (C:\Users\maris\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\script\EnhancedScript.js:52:26)
    at wrapEnhancedScript (C:\Users\maris\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\script\wrap-enhanced-script.js:21:28)
    at C:\Users\maris\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\script\index.js:39:27
    at Array.map (<anonymous>)
    at module.exports (C:\Users\maris\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\tasks\script\index.js:15:16)
    at module.exports (C:\Users\maris\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\helpers\state.js:8:12)
    at C:\Users\maris\AppData\Roaming\npm\node_modules\@nexrender\cli\node_modules\@nexrender\core\src\index.js:154:22 {
  code: 'ERR_INVALID_ARG_TYPE'
}`

is what i get when i try to use the module in a simple setup:

`{
    "template": {
        "src": "file:///e:/nexrender/test-template.aep",
        "composition": "maincomp",
        "outputModule": "H.264 - Match Render Settings - 15 Mbps",
        "outputExt": "mp4",
        "settingsTemplate": "Best Settings"
    },
    "actions": {
		"prerender": [
            {
                "module": "nexrender-comp-sequence",
                "sequence": [
                    {
                        "comp": "red5"
                    },
                    {
                        "comp": "blue8"
                    }
                ]
            }
        ],
        "postrender": [
            {
                "module": "@nexrender/action-copy",
                "output": "e:/Nexrender/test.mp4"
            }
        ]
    }
}`

**Comment by backbeatmedia** [comment]
Hello - I believe this problem is occurring when Nexrender is trying to 
build all the modules (in your case that's only the one I wrote) into a 
script that it can inject into After Effects. It looks to me like it 
can't find a file for some reason.

It's hard to guess where the problem lies, but maybe the module is not 
installed properly? I think you might get a better answer from Vladyslav 
as the code generating the error is under his control.

I've had this plugin working in my environment (which is also Windows). 
Not to say it isn't a problem with my code, but from the error report 
you supplied Nexrender it looks like hasn't got round to running my code 
yet.

All the best,

Jeremy




Jeremy Smith
Managing Director
Backbeat Media Services Ltd
www.bkbt.co.uk
+44 (0)7775 593007







------ Original Message ------
From "mp" ***@***.***>
To "backbeatmedia/nexrender-comp-sequence" 
***@***.***>
Cc "Subscribed" ***@***.***>
Date 20/12/2023 13:48:03
Subject [backbeatmedia/nexrender-comp-sequence] ERR_INVALID_ARG_TYPE 
while using Plugin in CLI (Issue #1)
